apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamlit-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-streamlit